import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeModeScript } from "flowbite-react";
import NavbarLandingPage from "./components/LandingPage/Navbar";
import FooterLandingPage from "./components/LandingPage/Footer";
import ContainerLandingPage from "./components/LandingPage/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IATL Veteran",
  description: "Generated by create next app",
};

export default function LandingPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${inter.className} antialiased dark:bg-gray-800`}>
        <ContainerLandingPage>
          <NavbarLandingPage />
          {children}
          <FooterLandingPage />
        </ContainerLandingPage>
      </body>
    </html>
  );
}
