import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeModeScript } from "flowbite-react";
import NavbarLandingPage from "./components/LandingPage/NavbarLandingPage";
import FooterLandingPage from "./components/LandingPage/FooterLandingPage";
import ContainerLandingPage from "./components/LandingPage/ContainerLandingPage";
import LandingPageLayout from "./components/Layout/LandingPageLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IATL Veteran",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${inter.className} antialiased dark:bg-gray-800`}>
        <LandingPageLayout>{children}</LandingPageLayout>
      </body>
    </html>
  );
}
